# Generated by Django 5.0.2 on 2024-04-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='pH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cay', models.CharField(max_length=50)),
                ('ph_can', models.CharField(max_length=10)),
                ('doam_can', models.CharField(max_length=10)),
            ],
        ),
    ]
