# Generated by Django 5.0.2 on 2024-04-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage', '0007_ph'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pH',
            new_name='pH_am',
        ),
    ]
